### ISSUE TITLE
Replace `plotrix` dependency

### ISSUE THREAD

**Issue by nicolerg** [kornl/mutoss#5]
CRAN has marked `plotrix`, which is a dependency for this package, as [orphaned](https://cran.r-project.org/web/packages/plotrix/index.html). `R CMD check` on an R package, e.g., via GitHub Actions, fails with the warning `Requires (indirectly) orphaned package: ‘plotrix’` if `mutoss` is a dependency (direct or indirect). See an example of a failed check [here](https://github.com/MoTrPAC/MotrpacRatTraining6mo/actions/runs/6807310238/job/18509950801).

**Comment by nicolerg** [comment]
As a temporary workaround, you can install `plotrix` from GitHub instead of CRAN, e.g.:
```
...
Imports: 
    plotrix
Remotes: 
    plotrix/plotrix
...
```

**Comment by kornl** [comment]
Hi, thanks for the note. But when I go to https://cran.r-project.org/web/checks/check_results_plotrix.html I see that plotrix was just updated today - I guess it's not orphaned anymore?

**Comment by kornl** [comment]
No, you are right. I'll take a look. Thanks again.

**Comment by kornl** [comment]
Duncan Murdoc wrote on R-pkg-devel yesterday that he "volunteered to take over maintenance of plotrix." and that he "should be
submitting a version without the "orphaned" designation soon."

**Comment by nicolerg** [comment]
Thanks!
